// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfyqlynxvjqyrhejxgcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmeXFseW54dmpxeXJoZWp4Z2NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NjQxMDQsImV4cCI6MjA2MDI0MDEwNH0.Rqmd6D17bEysWPrnwUI8myL3Mz1xipJpNZK2MIJm4Yc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);